---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

    - name: Install Jenkins dependencies
      community.general.zypper:
        name:
          - dejavu-fonts
          - fontconfig
          - java-11-openjdk
        state: present
      when: ansible_os_family == "Suse"

  roles:
    - role: geerlingguy.java
      when: ansible_os_family != "Suse"
    - role: geerlingguy.jenkins

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403
