---
# Debian.
- name: Update apt cache.
  apt: update_cache=true cache_valid_time=600
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Set the java_packages variable (Debian).
  set_fact:
    java_packages:
      - openjdk-8-jdk
  when: ansible_os_family == 'Debian'

# Red Hat.
- name: Set the java_packages variable (RedHat).
  set_fact:
    java_packages:
      - java-1.8.0-openjdk
  when: ansible_os_family == 'RedHat'
