---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_version: "2.346"

  pre_tasks:
    - include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Check installed version of Jenkins.
      command: rpm -q jenkins
      changed_when: false
      register: jenkins_rpm_version
      tags: ['skip_ansible_lint']

    - name: Print installed Jenkins package information.
      debug: var=jenkins_rpm_version

    - name: Fail if version doesn't match what we wanted.
      fail:
      when: "jenkins_version not in jenkins_rpm_version.stdout"
