---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_version: "1.644"
    jenkins_java_options:
      - "-Xmx1536m"
      - "-Xms768m"

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Check installed version of Jenkins.
      command: grep "{{ jenkins_java_options_env_var }}" "{{ jenkins_init_file }}"
      args:
        warn: false
      changed_when: false
      register: jenkins_grepped_java_options
      tags: ['skip_ansible_lint']

    - name: Print found java options
      debug: var=jenkins_grepped_java_options

    - name: Fail if our init addition isn't in the file
      fail:
      when: "'-Xmx1536m' not in jenkins_grepped_java_options.stdout"
